artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
    local_file_path: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

data_validation:
    root_dir: artifacts/data_validation
    dataset_path: artifacts/data_ingestion/winequality-red.csv
    STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
    root_dir: artifacts/data_transformation
    dataset_path: artifacts/data_ingestion/winequality-red.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
